name: Tests
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run shellcheck
        run: |
          sudo apt-get -qq update -y
          sudo apt-get -qq install shellcheck
          shellcheck src/*.sh
  bats:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run BATS
        run: |
          sudo apt-get -qq update -y
          sudo apt-get -qq install -y git
          git submodule init && git submodule update
          ./test/bats/bin/bats test/*.bats
