name: Tests
on: [push]
jobs:
  bats-testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Setup BATS
        run: |
          sudo apt-get -qq install -y git
          git --version
          git submodule init && git submodule update
          ./test/bats/bin/bats test/*.bats
